# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_ICLExact <- function(adj, z, verbose, eta0, zeta0, ap, aq, bp, bq, delta) {
    .Call(`_GreedySBTM_cpp_ICLExact`, adj, z, verbose, eta0, zeta0, ap, aq, bp, bq, delta)
}

cpp_GreedyICL <- function(adj, z, max_n_iter, verbose, eta0, zeta0, ap, aq, bp, bq, delta) {
    .Call(`_GreedySBTM_cpp_GreedyICL`, adj, z, max_n_iter, verbose, eta0, zeta0, ap, aq, bp, bq, delta)
}

cpp_GreedyMerge <- function(adj, z, verbose, eta0, zeta0, ap, aq, bp, bq, delta) {
    .Call(`_GreedySBTM_cpp_GreedyMerge`, adj, z, verbose, eta0, zeta0, ap, aq, bp, bq, delta)
}

cpp_CollapseLabels <- function(vec) {
    .Call(`_GreedySBTM_cpp_CollapseLabels`, vec)
}

